### ISSUE TITLE
 Physical robot

### ISSUE THREAD

**Issue by Alchemistqqqq** [TempleRAIL/nav-competition-icra2022-drl-vo#1]
Hello, I am very honored to read your paper and get your help in the simulation experiment a while ago. In your introduction, I saw that you used the turtlebot2 robot, but you used the Jackal robot in the competition. I would like to know if I can migrate this code to the turtlebot3 waffle pi for experiments in real environment. Because I am a beginner, if I can transfer to Waffle school for experiment, there may be some problems in the future, I hope you can give me some advice, thank you very much.

**Comment by zzuxzt** [comment]
Hi, thanks for your interest in our work. In principle, it should be able to be deployed on a Turtlebot 3 robot. The main concern is that I am not sure if the Raspberry Pi could run the DRL-VO policy in real time. But it's worth a good try. To do that, there are several key steps:
1) Follow our [paper](https://doi.org/10.1109/TRO.2023.3257549) (i.e. Sec.V.B) to modify the lidar historical map input based on your lidar sensor configuration (i.e. how many lidar scan points). Code files need to be modified: 
[barn_data_pub.py
](https://github.com/TempleRAIL/nav-competition-icra2022-drl-vo/blob/8b6ea3bf7251c55a62a6b026c1e2ac05d6ae1cb9/drl_vo/drl_vo_barn_nav/src/barn_data_pub.py#L34C1-L34C9)
[drl_vo_inference.py
](https://github.com/TempleRAIL/nav-competition-icra2022-drl-vo/blob/8b6ea3bf7251c55a62a6b026c1e2ac05d6ae1cb9/drl_vo/drl_vo_barn_nav/src/drl_vo_inference.py#L103C1-L130C76)
2) Find the control command topic for Turtlebot 3 and modify the topic in [drl_vo_inference.py](https://github.com/TempleRAIL/nav-competition-icra2022-drl-vo/blob/8b6ea3bf7251c55a62a6b026c1e2ac05d6ae1cb9/drl_vo/drl_vo_barn_nav/src/drl_vo_inference.py#L92C1-L92C90)
3) Try to install the singularity container software on the Raspberry Pi, then follow the ReadMe to depoly the DRL-VO policy; If it does not work, follow the ReadMe in [drl_vo_nav](https://github.com/TempleRAIL/drl_vo_nav) package to manually install learning-based packages:
```
pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
pip install gym==0.18.0 pandas==1.2.1
pip install stable-baselines3==1.1.0
pip install tensorboard psutil cloudpickle
```
After configuring the required environment you can depoly the DRL-VO policy to see how it works in the Turtlebot 3.

**Comment by Alchemistqqqq** [comment]
Thanks for your help, I will try the following real environment experiment according to your help.

**Comment by Alchemistqqqq** [comment]
Thanks for your help, I will try the following real environment experiment according to your help.
